package au.edu.unsw.soacourse.autochecks;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-06-06T16:18:57.804+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "AutoChecksServiceImplService", 
                  wsdlLocation = "http://localhost:8080/AutoChecksService/AutoChecksService?wsdl",
                  targetNamespace = "http://autochecks.soacourse.unsw.edu.au/") 
public class AutoChecksServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://autochecks.soacourse.unsw.edu.au/", "AutoChecksServiceImplService");
    public final static QName AutoChecksServiceImplPort = new QName("http://autochecks.soacourse.unsw.edu.au/", "AutoChecksServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/AutoChecksService/AutoChecksService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutoChecksServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/AutoChecksService/AutoChecksService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AutoChecksServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutoChecksServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutoChecksServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutoChecksServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutoChecksServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutoChecksServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns AutoChecksService
     */
    @WebEndpoint(name = "AutoChecksServiceImplPort")
    public AutoChecksService getAutoChecksServiceImplPort() {
        return super.getPort(AutoChecksServiceImplPort, AutoChecksService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoChecksService
     */
    @WebEndpoint(name = "AutoChecksServiceImplPort")
    public AutoChecksService getAutoChecksServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AutoChecksServiceImplPort, AutoChecksService.class, features);
    }

}
