package au.edu.unsw.soacourse.autochecks;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-06-06T16:18:57.795+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://autochecks.soacourse.unsw.edu.au", name = "AutoChecksService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AutoChecksService {

    @WebMethod(action = "http://autochecks.soacourse.unsw.edu.au/selector")
    @WebResult(name = "selectorResponse", targetNamespace = "http://autochecks.soacourse.unsw.edu.au", partName = "parameters")
    public SelectorResponse selector(
        @WebParam(partName = "parameters", name = "selectorRequest", targetNamespace = "http://autochecks.soacourse.unsw.edu.au")
        SelectorRequest parameters
    );

    @WebMethod(operationName = "DL", action = "http://autochecks.soacourse.unsw.edu.au/DL")
    @WebResult(name = "DLResponse", targetNamespace = "http://autochecks.soacourse.unsw.edu.au", partName = "parameters")
    public DLResponse dl(
        @WebParam(partName = "parameters", name = "DLRequest", targetNamespace = "http://autochecks.soacourse.unsw.edu.au")
        DLRequest parameters
    );

    @WebMethod(operationName = "ADR", action = "http://autochecks.soacourse.unsw.edu.au/ADR")
    @WebResult(name = "ADRResponse", targetNamespace = "http://autochecks.soacourse.unsw.edu.au", partName = "parameters")
    public ADRResponse adr(
        @WebParam(partName = "parameters", name = "ADRRequest", targetNamespace = "http://autochecks.soacourse.unsw.edu.au")
        ADRRequest parameters
    );
}
